language: php

sudo: false

branches:
  only:
    - master
    - develop
    - /^[0-9]+\.x$/
    - /^[0-9]+\.[0-9]+\.x$/
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: TYPO3_VERSION=^7.6
    - php: 5.6
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=~8.3.0
    - php: 7.0
      env: TYPO3_VERSION=~8.4.0
    - php: 7.0
      env: TYPO3_VERSION=~8.5.0
    - php: 7.0
      env: TYPO3_VERSION="dev-master as 8.5.0"
    - php: 7.1
      env: TYPO3_VERSION=^7.6
    - php: 7.1
      env: TYPO3_VERSION=^8
    - php: 7.1
      env: TYPO3_VERSION="dev-master as 8.5.0"
  allow_failures:
    - env: TYPO3_VERSION=~8.3.0
    - env: TYPO3_VERSION=~8.4.0
    - env: TYPO3_VERSION=~8.5.0
    - env: TYPO3_VERSION="dev-master as 8.5.0"

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

notifications:
  email:
    - typo3@evoweb.de

before_install:
  - echo $TRAVIS_PHP_VERSION
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - git clean -dffx
  - composer require --prefer-dist typo3/cms="$TYPO3_VERSION"
  - export TYPO3_PATH_WEB="$PWD/.Build/Web"
  - export PATH="$PATH:./Scripts"

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
    echo "$TYPO3_PATH_WEB";
    ls -la $TYPO3_PATH_WEB;

after_script:
  - >
    if [ -n "$TRAVIS_TAG" ] && [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
      echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"
      curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
      if [ $? -eq 0 ]; then
        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx

        # Build extension files
        composer extension-release

        # Upload
        TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${TRAVIS_TAG} to TER"
        .Build/bin/upload . "$TYPO3_ORG_USERNAME" "$TYPO3_ORG_PASSWORD" "$TAG_MESSAGE"
      fi;
    fi;

